# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Apurinã spellchecker"
apu = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Apurinã, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
apu = "TRANSLATE: A spellchecker for Apurinã, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.apu"

[windows]
system_product_code = "{1F169C9E-3152-4E7F-B66F-E2A475186894}_is1"
legacy_product_codes = [
    { value = "98C480D9-52E0-474D-B18C-7A1EB7C7EE4E", kind = "nsis" },
    { value = "0C947DF1-82FE-4C91-A2D0-ED546F2B7084", kind = "nsis" }
]
extra_locales = { apu-BR = "apu" }

[package.speller]
name = "Apurinã"
version = "0.1.1"

[package.grammar]
name = "Apurinã"
version = "0.1.0"

[package.tts-text-proc]
name = "Apurinã"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
