template = "https://github.com/giellalt/template-lang-und"
rev_id = 258
template_sha = "b5271fc37dc1cf0a7448e0553c24b3f857121d34"

[replacements]
__GLOTTOLOG_ID__ = "apur1254"
__REPO__ = "lang-apu"
__UND2C__ = "apu"
__UNDEFINED__ = "Apurin√£"
__UND__ = "apu"
