template = "https://github.com/giellalt/template-lang-und"
rev_id = 74
template_sha = "bdfb17f42e2c70deceee0362bc3db1bec5090f22"

[replacements]
__REPO__ = "lang-apu"
__UND2C__ = "apu"
__UNDEFINED__ = "Apurin√£"
__UND__ = "apu"
