template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "apur1254"
__REPO__ = "lang-apu"
__UND2C__ = "apu"
__UNDEFINED__ = "Apurin√£"
__UND__ = "apu"
