template = "https://github.com/giellalt/template-lang-und"
rev_id = 183
template_sha = "d0a0bae6ad6b62a4cd75ab409a3666d7362152b1"

[replacements]
__REPO__ = "lang-apu"
__UND2C__ = "apu"
__UNDEFINED__ = "Apurin√£"
__UND__ = "apu"
